# Generated by Django 5.2.5 on 2025-08-11 07:17

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, help_text='The date this article was originally published')),
                ('summary', models.TextField(help_text='A brief summary of the article (150-200 characters recommended)', max_length=500)),
                ('source_url', models.URLField(help_text='The original URL of the article')),
                ('source_name', models.CharField(default='Unknown', help_text='Name of the news source (e.g., BBC, Reuters)', max_length=100)),
                ('content_hash', models.CharField(help_text='Hash of the article content to prevent duplicates', max_length=64, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='When this article was scraped')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this article was last updated')),
            ],
            options={
                'verbose_name': 'News Article',
                'ordering': ['-publication_date', '-scraped_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the news section')),
            ],
            options={
                'verbose_name': 'News List Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
